import Head from 'next/head';
import { Inter } from 'next/font/google';
import Landing from '../components/Landing';
import List from '../components/List';
import Location from '../components/Location';
import axios from "axios";
import { useState } from 'react';
import Add from '../components/Add';
import AddButton from '../components/AddButton';
import Powered from '@/components/Poweredlatest';
import Reviews from '@/components/Reviewslatest';



const inter = Inter({ subsets: ['latin'] })

export default function Home({list, admin}) {
  const [close, setClose] = useState(true);



  return (
    <>
      <Head>
        <title>Smash Burger</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/imgs/ico.png" />
        <link href="https://unpkg.com/aos@2.3.1/dist/aos.css" rel="stylesheet"></link>
        <meta charSet='utf-8' />
      </Head>
      <Landing />
      {/* <Powered/> */}
      {/* {admin && <AddButton setClose={setClose}/> } */}
      <List list={list} />
      {/* {!close && <Add setClose={setClose}/> } */}
      <Location />
      <Reviews/>
      {/* <script src="https://unpkg.com/aos@2.3.1/dist/aos.js"></script>
      <script>
  AOS.init();
</script> */}
    </>
  )
}

export const getServerSideProps = async (ctx) => {
  const myCookie = ctx.req?.cookies || "";
  let admin = false;

  if (myCookie.token === process.env.TOKEN) {
    admin = true;
  }



  const res = await axios.get("https://small-res-coder-elzvq6ejs-smashsuez.vercel.app/api/products");
  return{
    props:{
      list: res.data,
      admin
    }
  }
}
